#!/usr/bin/env bash
# Get DNS record information for a subdomain

get_domain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  get_domain_info "$1" "www"
  get_domain_info "$1" "lb-01"
  get_domain_info "$1" "web-01"
  get_domain_info "$1" "web-02"

elif [ "$#" == 2 ]
then
  get_domain_info "$1" "$2"

fi
