#!/usr/bin/env bash
# Configures nginx server so that /redirect_me is redirecting to another page

if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y nginx
fi

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
