#!/usr/bin/env bash
# Nginx server custom 404 page that contains the string Ceci n'est pas une page

# Install Nginx if not already installed
if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y nginx
fi

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Create a custom Nginx configuration for the custom error page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}" | tee /etc/nginx/sites-available/custom_404 > /dev/null

ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

nginx -t

service nginx reload
