#!/usr/bin/env bash
# double number of servers

if ! [ -x "$(command -v nginx)" ]; then
    apt-get update
    apt-get install -y nginx
fi

cat <<EOF | tee /etc/nginx/sites-available/custom_header > /dev/null
server {
    listen 80 default_server;
    server_name _;
    add_header X-Served-By \$HOSTNAME;
    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF

ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

nginx -t

systemctl reload nginx
