#!/usr/bin/env bash
# Generates compressed archive of a MySQL db dump
mysql_user="root"
mysql_password="$1"
mysqldump -u "$mysql_user" -p"$mysql_password" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
