#!/usr/bin/env bash
# Nginx installation not listening on port 80

newport="80 default_server"
oldport="8080 default_server"
sed -i "s/$oldport/$newport/" /etc/nginx/sites-enabled/default

service nginx restart
