#!/usr/bin/env bash
# Script displays a list of currently running processes,
# showing all processes for all users, including those without a TTY
# in a user-oriented format, and showing the process hierarchy
# Using ps command with options to display the process list

ps -auxf
