#!/usr/bin/env bash
# Script displays "To infinity and beyond" indefinitely with a 2-second pause between each iteration.

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
