#!/usr/bin/env bash
#Script displays the time for 12 hours and 59 minutes.

hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    for ((minute=1; minute<=59; minute++))
    do
        echo "$minute"
    done
    ((hour++))
done
