#!/usr/bin/env bash
#Script displays the content of the current directory in a list format, showing only the part of the name after the first dash (if any).

for file in *
do
    if [[ $file != .* ]]
    then
        name=${file#*-}
        echo "$name"
    fi
done
